# Generated by Django 5.0 on 2023-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fero_ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
